---
title: "jaenna_data_exploration"
author: "Jaenna Wessling"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, include=FALSE, warning = FALSE, message = FALSE)

library(here)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(kableExtra)
library(dplyr)
library(stringr)
```

### Load in the new data

```{r, message = FALSE}
days_exceed <- read_csv(here("Tab3_Days_ExceedHealthBenchmarks.csv"))

# summary(days_exceed)

### By species 
### Days invert sed = max 381
### Days invertebrate water = max 250
### Days plant non-vascular = max 190 


### Days any species = max 381 (going to be from days invert sed
# unique(days_exceed$huc)


#### Creating a pivot longer df instead 
exceed_longer <- days_exceed %>% 
  pivot_longer(cols = days_fish:days_any_species, names_to = "species", values_to = "days") %>% 
  rename(application_sites = huc) 
```


### Plan of action
## Drop down menu to see days of exceedance by species & pesticide type 


### Wrangle by species

#### Fish
```{r}
fish <- exceed_longer %>% 
  select(huc, species, pesticide, days) %>% 
  filter(species == "days_fish") %>% 
  slice_max(days, n = 5) %>% # keeping the largest values of the counts by lake 
  arrange(-days) # arranges selected choices from greatest to least 
  

## Plot it 
ggplot(data = fish, aes(y = days, x = huc, fill = pesticide)) +
  scale_x_discrete(limits = fish$huc) +
  geom_col() +
  labs(y = 'Days of Exceedance', x = "Watershed",
       title = "Greatest Days of Exceedance for Fish Species") +
  theme(axis.text.x = element_text(angle =75, hjust = 1))
```


#### Inverts water
```{r}
invert_water <- exceed_longer %>% 
  select(species, pesticide, huc, days) %>% 
  filter(species == "days_invertebrate_water") %>% 
  slice_max(days, n = 5) %>% # keeping the largest values of the counts by lake
  arrange(-days) # arranges selected choices from greatest to least


## Plot it 
ggplot(data = invert_water, aes(y = days, x = huc, fill = pesticide)) +
  scale_x_discrete(limits = invert_water$huc) +
  geom_col() +
  labs(y = 'Days of Exceedance', x = "Watershed",
       title = "Greatest Days of Exceedance for Aquatic Invertabrate Species") +
  theme(axis.text.x = element_text(angle =75, hjust = 1))
```


#### Inverts sediment
```{r}
invert_sed <- exceed_longer %>% 
  select(species, pesticide, huc, days) %>% 
  filter(species == "days_invertebrate_sed") %>% 
  slice_max(days, n = 5) %>% # keeping the largest values of the counts by lake
  arrange(-days) # arranges selected choices from greatest to least


## Plot it 
ggplot(data = invert_sed, aes(y = days, x = huc, fill = pesticide)) +
  scale_x_discrete(limits = invert_sed$huc) +
  geom_col() +
  labs(y = 'Days of Exceedance', x = "Watershed",
       title = "Greatest Days of Exceedance for Sediment Invertabrate Species") +
  theme(axis.text.x = element_text(angle =75, hjust = 1))
```


#### Non-vascular plants 
```{r}
non_vasc_plant <- exceed_longer %>% 
  select(species, pesticide, huc, days) %>% 
  filter(species == "days_plant_nonvascular") %>% 
  slice_max(days, n = 5) %>% # keeping the largest values of the counts by lake
  arrange(-days) # arranges selected choices from greatest to least


## Plot it 
ggplot(data = non_vasc_plant, aes(y = days, x = huc, fill = pesticide)) +
  scale_x_discrete(limits = non_vasc_plant$huc) +
  geom_col() +
  labs(y = 'Days of Exceedance', x = "Watershed",
       title = "Greatest Days of Exceedance for Non-Vascular Plant Species") +
  theme(axis.text.x = element_text(angle =75, hjust = 1))
```

#### Vascular plants 
```{r}
vasc_plant <- exceed_longer %>% 
  select(species, pesticide, huc, days) %>% 
  filter(species == "days_plant_vascular") %>% 
  slice_max(days, n = 5) %>% # keeping the largest values of the counts by lake
  arrange(-days) # arranges selected choices from greatest to least


## Plot it 
ggplot(data = vasc_plant, aes(y = days, x = huc, fill = pesticide)) +
  scale_x_discrete(limits = vasc_plant$huc) +
  geom_col() +
  labs(y = 'Days of Exceedance', x = "Watershed",
       title = "Greatest Days of Exceedance for Vascular Plant Species") +
  theme(axis.text.x = element_text(angle =75, hjust = 1))
```


#### All species
```{r}
all_species <- exceed_longer %>% 
  select(species, pesticide, huc, days) %>% 
  filter(species == "days_any_species") %>% 
  slice_max(days, n = 5) %>% # keeping the largest values of the counts by lake
  arrange(-days) # arranges selected choices from greatest to least


## Plot it 
ggplot(data = all_species, aes(y = days, x = huc, fill = species)) +
  geom_col() +
  labs(y = 'Days of Exceedance', x = "Watershed",
       title = "Greatest Days of Exceedance for All Species") +
  theme(axis.text.x = element_text(angle =75, hjust = 1))
```


### By watershed???? 
```{r}
## Create a new dataframe where we can pull data from 
## Only want data that contains info from all species & has greater values than 0 


watershed_data <- exceed_longer %>% 
      select(species, pesticide, huc, days) %>% 
  filter(days > 0, species != "days_any_species")
```

